[build]
  command   = "npm run build"
  publish   = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from   = "/api/feedback-admin/*"
  to     = "/.netlify/functions/feedback-admin/:splat"
  status = 200

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
